language: c

os:
  - linux

env:
  - PYTHON_VER=2.7
  - PYTHON_VER=3.4

sudo: false

install:
  - if [[ "${PYTHON_VER:0:1}" == "2" ]]; then
      fn=Miniconda-latest-Linux-x86_64.sh;
    elif [[ "${PYTHON_VER:0:1}" == "3" ]]; then
      fn=Miniconda3-latest-Linux-x86_64.sh;
    fi

  - wget https://repo.continuum.io/miniconda/$fn -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda install -q conda-build anaconda-client

script:
  - conda info -a 
  - conda build -q --python $PYTHON_VER --no-anaconda-upload .
  - anaconda -t $ANACONDA_TOKEN upload -u maxirmx --force --no-progress $(conda build --python $PYTHON_VER --output .)

