language: c

os:
  - linux
  - osx

env:
  - PYTHON_VER=2.7
  - PYTHON_VER=3.4

sudo: false

install:
  - if [[ "${PYTHON_VER:0:1}" == "2" ]]; then
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        fn=Miniconda-latest-MacOSX-x86_64.sh;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        fn=Miniconda-latest-Linux-x86_64.sh;
      fi
    elif [[ "${PYTHON_VER:0:1}" == "3" ]]; then
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        fn=Miniconda3-latest-MacOSX-x86_64.sh;
      elif [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        fn=Miniconda3-latest-Linux-x86_64.sh;
      fi
    fi

  - wget https://repo.continuum.io/miniconda/$fn -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  - conda config --set always_yes yes --set changeps1 no
  - conda install -q conda-build anaconda-client

script:
  - conda info -a 
  - conda config --add channels maxirmx
  - conda build -q --python $PYTHON_VER --no-anaconda-upload .
  - anaconda -t $ANACONDA_TOKEN upload -u spacy --force --no-progress $(conda build --python $PYTHON_VER --output .)
