package:
  name: preshed
  version: "0.44"

source:
  fn: preshed-0.44.tar.gz
  url: https://pypi.python.org/packages/source/p/preshed/preshed-0.44.tar.gz
  md5: 240520aa623eabaefbca3d81e6dd032e

build:
  script: $PYTHON setup.py install
  # noarch_python: True

requirements:
  build:
    - python >=2.7
    - headers_workaround
    - murmurhash
    - cymem ==1.30

  run:
    - python >=2.7
    - headers_workaround
    - murmurhash
    - cymem ==1.30

test:
  imports:
    - preshed

about:
  home: https://github.com/syllog1sm/preshed
  license: MIT
  summary: 'Cython hash table that trusts the keys are pre-hashed'
