package:
  name: preshed
  version: "0.43"

source:
  fn: preshed-0.43.tar.gz
  url: https://pypi.python.org/packages/source/p/preshed/preshed-0.43.tar.gz
  md5: cad1ee9a06d267b2bc8feb3c0aa53f84

build:
  script: $PYTHON setup.py install
  # noarch_python: True

requirements:
  build:
    - python
    - headers_workaround
    - murmurhash
    - cymem

  run:
    - python
    - headers_workaround
    - murmurhash
    - cymem

test:
  imports:
    - preshed

about:
  home: https://github.com/syllog1sm/preshed
  license: MIT
  summary: 'Cython hash table that trusts the keys are pre-hashed'
