package:
  name: preshed
  version: "0.42"

source:
  fn: preshed-0.42.tar.gz
  url: https://pypi.python.org/packages/source/p/preshed/preshed-0.42.tar.gz
  md5: 7cae17b54bd3f4b4d2e5699ac57a53ad

build:
  script: $PYTHON setup.py install
  # noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - jinja2
    - headers_workaround
    - murmurhash
    - cymem

  run:
    - python
    - murmurhash
    - cymem

test:
  imports:
    - preshed

about:
  home: https://github.com/syllog1sm/preshed	
  summary: 'Cython hash table that trusts the keys are pre-hashed'
